spring:
  application:
    name: springwebfluxmono
  webflux:
    base-path: /api
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/test?authSource=admin
      database: test

logging:
  level:
    pe.joedayz.training.springwebfluxmono: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG